(TeX-add-style-hook
 "thesis"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("fontenc" "T2A") ("inputenc" "utf8x") ("babel" "english" "russian") ("graphicx" "pdftex")))
   (TeX-run-style-hooks
    "latex2e"
    "chapters/intro"
    "chapters/chapter1"
    "chapters/chapter2"
    "chapters/chapter3"
    "chapters/chapter4"
    "chapters/outro"
    "report"
    "rep10"
    "fontenc"
    "inputenc"
    "babel"
    "expdlist"
    "graphicx"
    "amsmath"
    "amssymb"
    "amsthm"
    "amsfonts"
    "amsxtra"
    "array"
    "wrapfig"
    "sty/dbl12"
    "srcltx"
    "epsfig"
    "verbatim"
    "sty/rac"
    "listings"
    "placeins"
    "caption"
    "subfigure"
    "easytable")
   (TeX-add-symbols
    '("todo" 1)
    "p"
    "t"
    "b"
    "tb"
    "cln"
    "pcn"
    "putImgx"
    "putImg"
    "drawfigure"
    "drawfigurex")
   (LaTeX-add-labels
    "#1"
    "#3")
   (LaTeX-add-environments
    "theorem"
    "prop"
    "corollary"
    "lemma"
    "question"
    "conjecture"
    "assumption"
    "definition"
    "notation"
    "condition"
    "example"
    "algorithm")
   (LaTeX-add-bibliographies)))

